title = "Perth Linux Users Group"
baseURL = "http://www.plug.org.au/"
languageCode = "en-au"
disablePathToLower = true
paginate = 50
enableGitInfo = true
enableRobotsTXT = true

[params]
github_username = "plugorgau"
twitter_username = "plugorgau"

[markup.goldmark.renderer]
unsafe = true

[permalinks]
minutes = "/events/committee/:year/:month-:day/"
