name: pull-request

on:
  push:
    pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Hugo
        run: sudo snap install --channel=extended/stable hugo
      - name: Try to build website
        run: hugo
